version: '3.8'
services:
  api:
    build:
        # dockerfile: D:\Documents\workspace\microservices-python\Dockerfile
        context: .
    image: flaskapp
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: pocket-broker.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://pbroker_user:<<password>>@localhost/pbroker
    networks:
      pgflaskapp:
    volumes:
      - ".:/app"
    depends_on:
      - "db"
    command: ["./entrypoint.sh"]

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: pbroker_user
      POSTGRES_PASSWORD: <<password>>
      POSTGRES_DB: pbroker
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    networks:
      pgflaskapp:
        aliases:
          - "postgres"

volumes:
  postgres-db:

networks:
  pgflaskapp:
    driver: bridge
