"""empty message

Revision ID: 0588b2e64264
Revises: c91547994777
Create Date: 2020-08-12 12:26:39.660795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0588b2e64264'
down_revision = 'c91547994777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('eventconfig_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'event_configs', ['eventconfig_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'eventconfig_id')
    # ### end Alembic commands ###
